name: bordered_text
description: Flutter plugin for applying subtle stroke to a Text widget. Supports Android and iOS.
version: 2.0.0
homepage: https://github.com/tewshi/bordered-text

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
