name: bordered_text
description: Apply a subtle stroke to a Text widget.
version: 0.0.1
author: tewshi<tjoe4u@gmail.com>
homepage: https://github.com/tewshi/bordered-text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
